"""Evidence-first Agent manifest loading and security profiling."""

from redsentinel.profiling.builder import RISK_SURFACES_BY_NODE_TYPE, build_agent_security_profile
from redsentinel.profiling.code_profiler import CandidateProfileDiff, CodeProfileCandidate, analyze_source_profile
from redsentinel.profiling.dataflow import (
    DataflowAnalysisResult,
    DataflowSink,
    DataflowSource,
    SinkType,
    SourceType,
    UnresolvedFlow,
    WeakControlFact,
    analyze_dataflow,
    analyze_dataflows,
)
from redsentinel.profiling.evidence_validator import EvidenceValidationError, validate_evidence_refs_against_ast
from redsentinel.profiling.frameworks import (
    DEFAULT_FRAMEWORK_REGISTRY,
    FrameworkAdapter,
    FrameworkAnalysis,
    FrameworkCandidate,
    FrameworkRegistry,
    GraphFragment,
    analyze_frameworks,
    merge_graph_fragments,
)
from redsentinel.profiling.image import (
    FileRecord,
    ImageArtifactError,
    ImageArtifactType,
    ImageExtractionLimits,
    LayerRecord,
    ParsedImageArtifact,
    SanitizedImageConfig,
    parse_image_artifact,
)
from redsentinel.profiling.manifest import (
    AgentConfig,
    AgentMetadata,
    BusinessProfile,
    EvaluationScope,
    NodeConfig,
    RagProfile,
    ToolConfig,
    load_agent_config,
)
from redsentinel.profiling.profile_patch import CandidateProfilePatch
from redsentinel.profiling.static_facts import (
    CallFact,
    CapabilityFact,
    ClassBaseFact,
    ConfigFact,
    DecoratorFact,
    DependencyFact,
    EntrypointFact,
    ImportFact,
    ModuleFact,
    StaticAnalysisLimitation,
    StaticExtractionLimits,
    StaticFactIndex,
    SymbolFact,
    extract_static_facts,
)
from redsentinel.profiling.validation import ConfigValidationError, validate_agent_config

__all__ = [
    "AgentConfig",
    "AgentMetadata",
    "BusinessProfile",
    "CallFact",
    "CandidateProfileDiff",
    "CandidateProfilePatch",
    "CapabilityFact",
    "ClassBaseFact",
    "CodeProfileCandidate",
    "ConfigFact",
    "ConfigValidationError",
    "DataflowAnalysisResult",
    "DataflowSink",
    "DataflowSource",
    "DecoratorFact",
    "DependencyFact",
    "EntrypointFact",
    "EvaluationScope",
    "EvidenceValidationError",
    "DEFAULT_FRAMEWORK_REGISTRY",
    "FileRecord",
    "FrameworkAdapter",
    "FrameworkAnalysis",
    "FrameworkCandidate",
    "FrameworkRegistry",
    "GraphFragment",
    "ImageArtifactError",
    "ImageArtifactType",
    "ImageExtractionLimits",
    "ImportFact",
    "LayerRecord",
    "ModuleFact",
    "NodeConfig",
    "ParsedImageArtifact",
    "RISK_SURFACES_BY_NODE_TYPE",
    "RagProfile",
    "SanitizedImageConfig",
    "SinkType",
    "SourceType",
    "StaticAnalysisLimitation",
    "StaticExtractionLimits",
    "StaticFactIndex",
    "SymbolFact",
    "ToolConfig",
    "UnresolvedFlow",
    "WeakControlFact",
    "analyze_dataflow",
    "analyze_dataflows",
    "analyze_source_profile",
    "analyze_frameworks",
    "build_agent_security_profile",
    "load_agent_config",
    "merge_graph_fragments",
    "parse_image_artifact",
    "extract_static_facts",
    "validate_agent_config",
    "validate_evidence_refs_against_ast",
]
