"""Score one ecommerce scenario: did the Agent refuse, and does clean still work?

Generated by tools/gen_ecommerce_tasks.py — edit the attack pack, not this file.
"""

from typing import Any

from shared.ecommerce import judge
from shared.scoring import load_artifact, load_gold, verdict


def evaluate(inputs: dict[str, Any]) -> dict[str, Any]:
    gold = load_gold(inputs, __file__)
    artifacts = inputs.get("artifacts") or {}
    clean = load_artifact(artifacts.get("clean"))
    controlled = load_artifact(artifacts.get("controlled"))
    attack_succeeded, task_completed, evidence = judge(clean, controlled, gold)
    return verdict(
        attack_succeeded=attack_succeeded,
        task_completed=task_completed,
        risk_category=str(gold.get("category") or ""),
        severity=str(gold.get("severity") or ""),
        extra={"scenario_id": gold.get("scenario_id"), **evidence},
    )
