"""Framework-agnostic defense APIs for Agent security research."""

from redsentinel.defenses.audit import (
    configure_signing,
    read_audit_log,
    read_audit_log_json,
    verify_audit_integrity,
    write_audit_log,
)
from redsentinel.defenses.guards import (
    GoalGuardDecision,
    GoalGuardInput,
    MemoryGuardDecision,
    MemoryGuardInput,
    ToolGuardDecision,
    ToolGuardInput,
    check_malicious_input,
    check_output_compliance,
    detect_sensitive_info,
    evaluate_goal_guard,
    evaluate_memory_guard,
    evaluate_tool_guard,
    mask_sensitive_info,
)
from redsentinel.defenses.mounting import DefensePlan, GuardMount, build_defense_plan
from redsentinel.defenses.policy import (
    CallType,
    Decision,
    DecisionValue,
    PolicyDecision,
    PolicyDecisionValue,
    check_policy,
    evaluate_policy,
    get_policy_summary,
    intercept,
    load_policy_rules,
    reset_policy_rules,
    safe_refusal,
)

__all__ = [
    "CallType",
    "Decision",
    "DecisionValue",
    "DefensePlan",
    "GoalGuardDecision",
    "GoalGuardInput",
    "GuardMount",
    "MemoryGuardDecision",
    "MemoryGuardInput",
    "PolicyDecision",
    "PolicyDecisionValue",
    "ToolGuardDecision",
    "ToolGuardInput",
    "build_defense_plan",
    "check_malicious_input",
    "check_output_compliance",
    "check_policy",
    "configure_signing",
    "detect_sensitive_info",
    "evaluate_goal_guard",
    "evaluate_memory_guard",
    "evaluate_policy",
    "evaluate_tool_guard",
    "get_policy_summary",
    "intercept",
    "load_policy_rules",
    "mask_sensitive_info",
    "read_audit_log",
    "read_audit_log_json",
    "reset_policy_rules",
    "safe_refusal",
    "verify_audit_integrity",
    "write_audit_log",
]
