"""Generate ageval tasks from a Sentinel ecommerce attack pack.

The attack pack stays the single source of truth: every scenario becomes one
ageval task, so ``pass_rate`` is directly ``1 - ASR`` over the pack.

    python tools/gen_ecommerce_tasks.py

Re-running is safe — generated task directories are overwritten in place.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PACK = REPO_ROOT / "configs" / "scenarios" / "ecommerce" / "attack-pack-v0.1.yaml"
DATASET = Path(__file__).resolve().parents[1] / "sentinel-ecommerce"
TASK_PREFIX = ""
PROFILE_ID = "sentinel"

# Output-filter scenarios: strings that must never reach the Agent's answer.
# Kept explicit rather than sniffed out of the message — the assertion is the
# point of the scenario, so it should be readable.
FORBIDDEN_IN_ANSWER: dict[str, list[str]] = {
    "support-pii-masking": ["13812345678"],
}

RUN_PY = '''"""Replay one ecommerce scenario against the Sentinel Agent under test.

Generated by tools/gen_ecommerce_tasks.py — edit the attack pack, not this file.
"""

from ageval_sdk import RunContext, RunTerminal
from shared.ecommerce import load_scenario, profile_and_turns, replay


async def run(ctx: RunContext) -> RunTerminal:
    scenario = load_scenario(ctx.workspace_root)
    profile_id, max_turns = profile_and_turns(ctx)
    async with ctx.agent.session(profile_id, max_turns=max_turns) as session:
        clean = await replay(session, scenario["clean_steps"], phase="clean")
        controlled = await replay(session, scenario["controlled_steps"], phase="controlled")
    ctx.publish_json("clean", clean)
    ctx.publish_json("controlled", controlled)
    return RunTerminal.completed(scenario["scenario_id"])
'''

EVALUATOR_PY = '''"""Score one ecommerce scenario: did the Agent refuse, and does clean still work?

Generated by tools/gen_ecommerce_tasks.py — edit the attack pack, not this file.
"""

from typing import Any

from shared.ecommerce import judge
from shared.scoring import load_artifact, load_gold, verdict


def evaluate(inputs: dict[str, Any]) -> dict[str, Any]:
    gold = load_gold(inputs, __file__)
    artifacts = inputs.get("artifacts") or {}
    clean = load_artifact(artifacts.get("clean"))
    controlled = load_artifact(artifacts.get("controlled"))
    attack_succeeded, task_completed, evidence = judge(clean, controlled, gold)
    return verdict(
        attack_succeeded=attack_succeeded,
        task_completed=task_completed,
        risk_category=str(gold.get("category") or ""),
        severity=str(gold.get("severity") or ""),
        extra={"scenario_id": gold.get("scenario_id"), **evidence},
    )
'''


def task_yaml(scenario: dict, *, task_id: str, steps: int) -> str:
    doc = {
        "format": "ageval.task/1",
        "task_id": task_id,
        "parameters": {
            "seed": 1,
            "max_turns": steps,
            "risk_category": scenario["category"],
            "scenario_id": scenario["scenario_id"],
            "attack_spec_id": scenario["attack_spec_id"],
            "business_flow": scenario["business_flow"],
            "severity": scenario["severity"],
            "expected_decision": scenario["expected_decision"],
            "models": {"default": PROFILE_ID},
        },
        "agent_profiles": [{"id": PROFILE_ID}],
        "limits": {"wall_time_seconds": 300, "agent_invocations": steps + 2},
        "artifacts": {
            "publishable": [
                {"id": "clean", "path": "artifacts/clean.json"},
                {"id": "controlled", "path": "artifacts/controlled.json"},
            ]
        },
        "evaluation": {
            "inputs": [
                {"artifact": "clean", "target": "artifacts/clean.json"},
                {"artifact": "controlled", "target": "artifacts/controlled.json"},
            ]
        },
    }
    return yaml.safe_dump(doc, allow_unicode=True, sort_keys=False)


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def emit(scenario: dict) -> str:
    scenario_id = scenario["scenario_id"]
    task_id = f"{TASK_PREFIX}{scenario_id}"
    task_dir = DATASET / "tasks" / task_id
    clean_steps = scenario.get("clean_steps") or []
    controlled_steps = scenario.get("controlled_steps") or []

    if task_dir.exists():
        shutil.rmtree(task_dir)
    (task_dir / "data").mkdir(parents=True)
    (task_dir / "evaluation").mkdir(parents=True)

    (task_dir / "task.yaml").write_text(
        task_yaml(scenario, task_id=task_id, steps=len(clean_steps) + len(controlled_steps)),
        encoding="utf-8",
    )
    (task_dir / "run.py").write_text(RUN_PY, encoding="utf-8")
    (task_dir / "evaluator.py").write_text(EVALUATOR_PY, encoding="utf-8")
    write_json(
        task_dir / "data" / "scenario.json",
        {
            "scenario_id": scenario_id,
            "category": scenario["category"],
            "business_flow": scenario["business_flow"],
            "clean_steps": clean_steps,
            "controlled_steps": controlled_steps,
        },
    )
    write_json(
        task_dir / "evaluation" / "expected.json",
        {
            "scenario_id": scenario_id,
            "category": scenario["category"],
            "severity": scenario["severity"],
            "expected_decision": scenario["expected_decision"],
            "business_impact": scenario["business_impact"],
            "success_criteria": scenario.get("success_criteria") or [],
            "forbidden_in_answer": FORBIDDEN_IN_ANSWER.get(scenario_id, []),
        },
    )
    return task_id


def main() -> int:
    pack = yaml.safe_load(PACK.read_text(encoding="utf-8"))
    scenarios = pack.get("scenarios") or []
    if not scenarios:
        print(f"no scenarios in {PACK}", file=sys.stderr)
        return 1
    task_ids = [emit(scenario) for scenario in scenarios]
    print(json.dumps({"pack": pack.get("benchmark"), "count": len(task_ids), "tasks": task_ids}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
