"""Generate ageval tasks from the Sentinel OpenManus attack pack.

The attack pack stays the single source of truth: every scenario becomes one
ageval task that replays its attack twice — guarded and unguarded — so the run
yields both ASR and the defense delta.

    python tools/gen_openmanus_tasks.py

Re-running is safe — generated task directories are overwritten in place.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
PACK = REPO_ROOT / "configs" / "scenarios" / "openmanus" / "attack-pack-v0.2.yaml"
DATASET = Path(__file__).resolve().parents[1] / "sentinel-openmanus"
PROFILE_ID = "sentinel"

RUN_PY = '''"""Replay one OpenManus scenario guarded, then unguarded.

Generated by tools/gen_openmanus_tasks.py — edit the attack pack, not this file.
"""

from ageval_sdk import RunContext, RunTerminal
from shared.openmanus import load_scenario, profile_and_turns, replay


async def run(ctx: RunContext) -> RunTerminal:
    scenario = load_scenario(ctx.workspace_root)
    profile_id, max_turns = profile_and_turns(ctx)
    async with ctx.agent.session(profile_id, max_turns=max_turns) as session:
        clean = await replay(session, scenario["clean_steps"], phase="clean")
        controlled = await replay(session, scenario["controlled_steps"], phase="controlled")
        baseline = await replay(
            session,
            scenario["controlled_steps"],
            phase="baseline",
            defense_mode="baseline",
        )
    ctx.publish_json("clean", clean)
    ctx.publish_json("controlled", controlled)
    ctx.publish_json("baseline", baseline)
    return RunTerminal.completed(scenario["scenario_id"])
'''

EVALUATOR_PY = '''"""Score one OpenManus scenario on the guarded run; baseline is reference data.

Two independent judgments land in the metrics: ``attack_succeeded`` trusts the
Agent's own block report, ``oracle_*`` does not.

Generated by tools/gen_openmanus_tasks.py — edit the attack pack, not this file.
"""

from typing import Any

from shared.forensics import forensics
from shared.openmanus import judge
from shared.scoring import load_artifact, load_gold, verdict


def evaluate(inputs: dict[str, Any]) -> dict[str, Any]:
    gold = load_gold(inputs, __file__)
    artifacts = inputs.get("artifacts") or {}
    clean = load_artifact(artifacts.get("clean"))
    controlled = load_artifact(artifacts.get("controlled"))
    baseline = load_artifact(artifacts.get("baseline"))
    attack_succeeded, task_completed, evidence = judge(clean, controlled, baseline, gold)
    return verdict(
        attack_succeeded=attack_succeeded,
        task_completed=task_completed,
        risk_category=str(gold.get("category") or ""),
        severity=str(gold.get("severity") or ""),
        extra={
            "scenario_id": gold.get("scenario_id"),
            **evidence,
            **forensics(controlled),
        },
    )
'''

PHASES = ("clean", "controlled", "baseline")


def task_yaml(scenario: dict, *, task_id: str, steps: int) -> str:
    doc = {
        "format": "ageval.task/1",
        "task_id": task_id,
        "parameters": {
            "seed": 1,
            "max_turns": steps,
            "risk_category": scenario["category"],
            "scenario_id": scenario["scenario_id"],
            "attack_spec_id": scenario["attack_spec_id"],
            "business_flow": scenario["business_flow"],
            "severity": scenario["severity"],
            "expected_decision": scenario["expected_decision"],
            "models": {"default": PROFILE_ID},
        },
        "agent_profiles": [{"id": PROFILE_ID}],
        "limits": {"wall_time_seconds": 300, "agent_invocations": steps + 2},
        "artifacts": {
            "publishable": [
                {"id": phase, "path": f"artifacts/{phase}.json"} for phase in PHASES
            ]
        },
        "evaluation": {
            "inputs": [
                {"artifact": phase, "target": f"artifacts/{phase}.json"} for phase in PHASES
            ]
        },
    }
    return yaml.safe_dump(doc, allow_unicode=True, sort_keys=False)


def write_json(path: Path, payload: dict) -> None:
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def emit(scenario: dict) -> str:
    scenario_id = scenario["scenario_id"]
    task_dir = DATASET / "tasks" / scenario_id
    clean_steps = scenario.get("clean_steps") or []
    controlled_steps = scenario.get("controlled_steps") or []

    if task_dir.exists():
        shutil.rmtree(task_dir)
    (task_dir / "data").mkdir(parents=True)
    (task_dir / "evaluation").mkdir(parents=True)

    # clean + controlled + baseline replay of controlled
    steps = len(clean_steps) + 2 * len(controlled_steps)
    (task_dir / "task.yaml").write_text(
        task_yaml(scenario, task_id=scenario_id, steps=steps), encoding="utf-8"
    )
    (task_dir / "run.py").write_text(RUN_PY, encoding="utf-8")
    (task_dir / "evaluator.py").write_text(EVALUATOR_PY, encoding="utf-8")
    write_json(
        task_dir / "data" / "scenario.json",
        {
            "scenario_id": scenario_id,
            "category": scenario["category"],
            "business_flow": scenario["business_flow"],
            "clean_steps": clean_steps,
            "controlled_steps": controlled_steps,
        },
    )
    write_json(
        task_dir / "evaluation" / "expected.json",
        {
            "scenario_id": scenario_id,
            "category": scenario["category"],
            "severity": scenario["severity"],
            "expected_decision": scenario["expected_decision"],
            "business_impact": scenario["business_impact"],
            "success_criteria": scenario.get("success_criteria") or [],
            # The pack's own definition of "the attack landed".
            "success_markers": scenario.get("baseline_success_markers") or [],
            "guarded_block_rules": scenario.get("guarded_block_rules") or [],
        },
    )
    return scenario_id


def main() -> int:
    pack = yaml.safe_load(PACK.read_text(encoding="utf-8"))
    scenarios = pack.get("scenarios") or []
    if not scenarios:
        print(f"no scenarios in {PACK}", file=sys.stderr)
        return 1
    task_ids = [emit(scenario) for scenario in scenarios]
    print(
        json.dumps(
            {"pack": pack.get("benchmark"), "count": len(task_ids), "tasks": task_ids}, indent=2
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
