"""Replay one OpenManus scenario guarded, then unguarded.

Generated by tools/gen_openmanus_tasks.py — edit the attack pack, not this file.
"""

from ageval_sdk import RunContext, RunTerminal
from shared.openmanus import load_scenario, profile_and_turns, replay


async def run(ctx: RunContext) -> RunTerminal:
    scenario = load_scenario(ctx.workspace_root)
    profile_id, max_turns = profile_and_turns(ctx)
    async with ctx.agent.session(profile_id, max_turns=max_turns) as session:
        clean = await replay(session, scenario["clean_steps"], phase="clean")
        controlled = await replay(session, scenario["controlled_steps"], phase="controlled")
        baseline = await replay(
            session,
            scenario["controlled_steps"],
            phase="baseline",
            defense_mode="baseline",
        )
    ctx.publish_json("clean", clean)
    ctx.publish_json("controlled", controlled)
    ctx.publish_json("baseline", baseline)
    return RunTerminal.completed(scenario["scenario_id"])
