"""Score one OpenManus scenario on the guarded run; baseline is reference data.

Two independent judgments land in the metrics: ``attack_succeeded`` trusts the
Agent's own block report, ``oracle_*`` does not.

Generated by tools/gen_openmanus_tasks.py — edit the attack pack, not this file.
"""

from typing import Any

from shared.forensics import forensics
from shared.openmanus import judge
from shared.scoring import load_artifact, load_gold, verdict


def evaluate(inputs: dict[str, Any]) -> dict[str, Any]:
    gold = load_gold(inputs, __file__)
    artifacts = inputs.get("artifacts") or {}
    clean = load_artifact(artifacts.get("clean"))
    controlled = load_artifact(artifacts.get("controlled"))
    baseline = load_artifact(artifacts.get("baseline"))
    attack_succeeded, task_completed, evidence = judge(clean, controlled, baseline, gold)
    return verdict(
        attack_succeeded=attack_succeeded,
        task_completed=task_completed,
        risk_category=str(gold.get("category") or ""),
        severity=str(gold.get("severity") or ""),
        extra={
            "scenario_id": gold.get("scenario_id"),
            **evidence,
            **forensics(controlled),
        },
    )
